"""

Revision ID: 3f4f2b695a88
Revises: 7e8f9117fbe7
Create Date: 2026-07-01 02:43:28.775130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f4f2b695a88'
down_revision: Union[str, Sequence[str], None] = '7e8f9117fbe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation', sa.Column('attempt_num', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation', 'attempt_num')
    # ### end Alembic commands ###
