"""initial schema

Revision ID: 7e8f9117fbe7
Revises: 
Create Date: 2026-06-28 00:02:58.940088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e8f9117fbe7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.Text(), nullable=False),
    sa.Column('archive_file_name', sa.Text(), nullable=True),
    sa.Column('file_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('added_on', sa.Integer(), server_default=sa.text("(CAST(strftime('%s','now') AS INTEGER))"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('project_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('added_on', sa.Integer(), server_default=sa.text("(CAST(strftime('%s','now') AS INTEGER))"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('added_on', sa.Integer(), server_default=sa.text("(CAST(strftime('%s','now') AS INTEGER))"), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('added_on', sa.Integer(), server_default=sa.text("(CAST(strftime('%s','now') AS INTEGER))"), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('added_on', sa.Integer(), server_default=sa.text("(CAST(strftime('%s','now') AS INTEGER))"), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clip.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('shot_id', sa.Integer(), nullable=True),
    sa.Column('workflow_name', sa.Text(), nullable=True),
    sa.Column('workflow_id', sa.Text(), nullable=True),
    sa.Column('workflow_type', sa.Text(), nullable=True),
    sa.Column('generation_time_seconds', sa.Float(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('requested_width', sa.Integer(), nullable=True),
    sa.Column('requested_height', sa.Integer(), nullable=True),
    sa.Column('output_width', sa.Integer(), nullable=True),
    sa.Column('output_height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('sampler', sa.Text(), nullable=True),
    sa.Column('scheduler', sa.Text(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('cfg', sa.Float(), nullable=True),
    sa.Column('primary_model_name', sa.Text(), nullable=True),
    sa.Column('models_json', sa.JSON(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('all_prompts_json', sa.JSON(), nullable=True),
    sa.Column('input_files_count', sa.Integer(), nullable=True),
    sa.Column('raw_intent', sa.Text(), nullable=True),
    sa.Column('raw_review', sa.Text(), nullable=True),
    sa.Column('cleaned_intent', sa.Text(), nullable=True),
    sa.Column('cleaned_review', sa.Text(), nullable=True),
    sa.Column('failure_description', sa.Text(), nullable=True),
    sa.Column('suspected_causes', sa.Text(), nullable=True),
    sa.Column('correction_strategy', sa.Text(), nullable=True),
    sa.Column('accepted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('added_on', sa.Integer(), server_default=sa.text("(CAST(strftime('%s','now') AS INTEGER))"), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['shot_id'], ['shot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('assoc_type', sa.Enum('INPUT', 'OUTPUT', name='assoctype'), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generation_id'], ['generation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generation_id', 'asset_id', 'role', name='uq_generation_asset')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generation_asset')
    op.drop_table('generation')
    op.drop_table('shot')
    op.drop_table('clip')
    op.drop_table('scene')
    op.drop_table('project')
    op.drop_table('asset')
    # ### end Alembic commands ###
